<?php

return [
    "Al Jasra",
    "Al Hamala",
    "Hidd",
    "Al Lawzi",
    "Damistan",
    "Karzakan",
    "Al Malkiya",
    "Sadad",
    "Al Safriya",
    "Shahrakan",
    "Dar Kulaib",
    "Zallaq",
    "Belaj Al Jazair",
    "Sakheer",
    "Hlaitan",
    "Wadi Ali",
    "Mamlahat Al Mamtala",
    "Umm Al Naasan",
    "King Fahad Causway",
    "Al Mamtala",
    "Hawar",
    "Umm Hazwarah ( Hawar )",
    "Southern sawad ( Hawar )",
    "Northern sawad ( Hawar )",
    "Hidd Industrial Area",
    "Hamad Town",
    "Hammad town ( Hawar )",
    "Muharaq",
    "Muharraq",
    "Busaiteen",
    "Al Sayh",
    "Al Dair",
    "Samaheej",
    "Arad",
    "Halat Alsulta",
    "Halat Alnaim",
    "Galali",
    "Amwaj",
    "Diyar Al Muharraq",
    "Dilmunia",
    "MANAMA SOUQ",
    "Al Noaim",
    "Manama",
    "RAS RUMAN",
    "QUDAIBIYA",
    "AL SALMANIA",
    "ALQUFOOL",
    "Diplomatic Area",
    "HOORA",
    "Alcornish",
    "ALFATEH",
    "ADLIYA",
    "BU ASHIRA",
    "BU GHAZAL",
    "Um Alhassam",
    "MAHOOZ",
    "JUFFAIR",
    "GURAIFA",
    "Minaa Salman",
    "AL-SOWAIFIA",
    "ALBURHAMA",
    "AL SALHIYAH",
    "ZINJ",
    "BILAD AL-QADEEM",
    "Al Khamis",
    "Adhari",
    "Abu Buham",
    "Southern Sehla",
    "Nabih Salih",
    "Sanabis",
    "Tashan",
    "Al Musalla",
    "Daih",
    "Jidhafs",
    "Seef Area",
    "Karbabad",
    "Jabalt Hibshi",
    "Al Qala'a",
    "Northern Sehla",
    "AL-MAQSHA",
    "Al Qadam",
    "Al Magshaa",
    "Karana",
    "Bu Quwa",
    "Al Hajar",
    "Abu Saiba'a",
    "Al Shakhura",
    "Jannusan",
    "Magaba",
    "Jid Al Haj",
    "Saar",
    "Barbar",
    "Al Markh",
    "Diraz",
    "Bani Jamra",
    "Al Quraya",
    "Budaiya",
    "Janabiya",
    "Northern City",
    "Almuhammadiyah",
    "Jedah",
    "Nurana",
    "Sitra Industrial Area",
    "Mahaza",
    "Al Qarya",
    "Murgoban",
    "Al Kharjiya",
    "Abu Al Aish",
    "Wadyan",
    "Sufala",
    "Al Hamriya",
    "Juzur Al Dar",
    "Um Albaidh",
    "East Sitra City",
    "Eastern Aker",
    "Western Aker",
    "Maameer",
    "Nuwaydirat",
    "Hawrat Sanad",
    "Tubli",
    "Salmabad",
    "Hoarat A'ali",
    "Al Ramli",
    "Zayed Town",
    "Jid Ali",
    "Jurdab",
    "A'ali",
    "Al Nasfa",
    "Sanad",
    "Buri",
    "Isa Town",
    "Al Hunaniya",
    "West Riffa",
    "East Riffa",
    "Al Rawdha",
    "Bu Kuwarah",
    "Riffa North",
    "Jari Al Shaikh",
    "Wadi Al Sail",
    "Al Hajyat",
    "South wadi al sail",
    "Al Buhair",
    "Swaidrah",
    "Al Mazrooeeah",
    "Safrah",
    "Awali",
    "Al Reqa",
    "Al Hessy",
    "Al Moaaskar",
    "Askar",
    "Ras Zuwaid",
    "Mazraa",
    "Ras Abu Jarjor",
    "Hafeera",
    "jaw",
    "Ras Hayan",
    "Al Gainah",
    "BAR AL DUR",
    "Al Door",
    "Al Qareen",
    "Al Jaseera",
    "Jad Al Jamal",
    "Sukhair",
    "Al Rasameen",
    "Msainsat",
    "Um Jadir",
    "Al Qarah",
    "Al Omar",
    "Al Shabak",
    "Al Romaitha",
    "Um Jder Al Saman",
    "Trafi",
    "Durrat AL Bahrain",
    "Trabzon",
    "Istanbul"
];
